# Generated by Django 2.2.4 on 2020-11-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200510_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'EN VENTA'), ('N', 'NUEVO'), ('P', 'PROMOCION')], max_length=1),
        ),
    ]
